### ISSUE TITLE
CSS Injected globally from App.css

### ISSUE THREAD

**Issue by builtbyproxy** [satendra02/react-chrome-extension#24]
# Hello

First off thanks for this awesome repo and especially your [amazing medium article](https://itnext.io/create-chrome-extension-with-reactjs-using-inject-page-strategy-137650de1f39).

# What's Wrong

I'm having a slight issue with the `app.css` being injected into my page regardless of me wrapping the actual usage of App in a `frame` component from `react-frame-component`. 

For example: 
I have defined my `app.css` file to have the className: `css-19rsoyj` which at this point in time happens to be the same className shared by the header on [reactjs.org](https://reactjs.org/)
![image](https://user-images.githubusercontent.com/16897508/81563823-2324f680-93da-11ea-965a-10c9a068ed6a.png)

However, when I do this, the `app.css` file which is being imported into my `app.js` file, which is then imported into `content.js` to be rendered, will affect that class with the following result: 
![image](https://user-images.githubusercontent.com/16897508/81563986-667f6500-93da-11ea-9342-97a333353e7f.png)

I don't have an image editor however if you look at the `CSS` styling for this div with the afore-mentioned class name, you can see styles being applied, despite being overridden after. 

I have had this issue where if I had a class `container` it would override another site's container css making the website un-usable. 

# What have I tried:

I've tried a number of things to debug and validate this problem, they aren't in-depth but I hope they can provide some clarity with where I'm at:

- Disable the `app.css` import in the `app.js` file. This removes the css injection confirming this is where the problem is 'originating' from. 
- Attempt to wrap the HTML code in `app.js` in a frame from `react-frame-component`. This did not work
- disable the import with JS and instead tried: `el="stylesheet" href={chrome.runtime.getURL("/static/css/app.css")}`. This did not work either. 

# Conclusion

Any assistance would be great! So far I'm only having cosmetic issues however if this goes live as it is, it will break a lot of people stuff which I don't want happening. Thanks again for putting this together! I hope my issue is clear, it's a little tricky to explain everything haha!

**Comment by builtbyproxy** [comment]
As a bit of an update on this with some further digging!
My `content.js` file basically looks like this: 
```
/*global chrome*/
import React from 'react';
import ReactDOM from 'react-dom';
import Frame, { FrameContextConsumer }from 'react-frame-component';
import App from "./app";
import "./content.css";

class Main extends React.Component {
  render() {
    return (
      <Frame head={[<link type="text/css" rel="stylesheet" href={chrome.runtime.getURL("/static/css/content.css")} ></link>]}> 
        <FrameContextConsumer>
        {
        // Callback is invoked with iframe's window and document instances
          ({document, window}) => {
            // return <div />
            return <App document={document} window={window} isExt={true}/> 
          }
        }
        </FrameContextConsumer>
      </Frame>
    )
  }
}
```

To note here are the `import "./content.css";` and the `import App from "./app";` lines.

`content.css` only has this: 
```
/* src/content.css */
.norm-extension {
   padding: 20px;
}
.norm-extension h1 {
    color: #000;
}
```

and then `App` is just the regular `App` from your master branch. 
However, when I build this, `static/css/content.css` is loading in with `app.css` css bundled in, most likely from the `App` render. 
Primarily these lines though: 
![image](https://user-images.githubusercontent.com/16897508/81565786-44d3ad00-93dd-11ea-8efa-44ed6a947582.png)

Not sure if that helps but the CSS is being bundled into `content.css` once it's all built. Any help is always appreciated! Thank you!

**Comment by satendra02** [comment]
Hi @builtbyproxy 

I am glad that you liked this repo and thanks for asking this question. 

Yes, this issue is really serious, and going to create a lot of trouble in production.

To solve this there are a few things we need to look at the current implementation.

### OVERVIEW
1. There are two entry points for our app `index.js` and `content.js`.
```
// config/webpack.config.prod.js
entry: {
    app: [require.resolve('./polyfills'), paths.appIndexJs],
    content: [require.resolve('./polyfills'), './src/content.js']
},
```
`index.js` is used when we run the app with web server in the browser and `content.js` is used for extension. 

2. So as per our current implementation, `index.js` imports `index.css` and `App` component which further imports `App.css` similarly `content.js` imports `content.css` and `App` component which further imports `App.css`.

3. Now `app.css` and `content.css` is created on the build inside the `static` folder and contain all the CSS  used inside `index.js` and  `content.js` respectively

### PROBLEM

From both entries `App.css` is common because we are using `App` component in both files `index.js` and `content.js`, So its code, is copied in both `app.css` and `content.css` after build and in our `manifest.json` we are using `app.css` in **content_scripts** section.

```
//public/manifest.json
...
"content_scripts" : [
    {
      "matches": [ "<all_urls>" ],
      "css": ["/static/css/app.css"],
      "js": ["/static/js/content.js"]
    }
  ],
...
```
We know that _css_ used as **content_scripts** is directly injected on the host page and it can affect host page styling if not used properly.

Also, we didn't want our `App.css` code outside iframe because it must be used to style extension HTML. 

So as **content_scripts** CSS, We need to include only those CSS properties which are responsible for the position of **root div** which means we need only `index.css` code as **content_scripts** as per current implementation.

### SOLUTION
 
Follow the below steps to fix the problem

- Create a new file `root.css` inside `public/css` folder.
- Cut-paste `index.css` code in `root.css` file.
- Now change `manifest.json` file CSS entry

```
"css": ["/css/root.css"]
```

Make sure `root.css` will only contain CSS to style your root div.
Make sure all the CSS class names in `root.css` are unique so that it doesn't conflict with host page class names.

Now we are already using `content.css` inside an iframe in `content.js` means `App.css` is now only restricted to iframe.
```
<Frame head={[<link type="text/css" rel="stylesheet" href={chrome.runtime.getURL("/static/css/content.css")} ></link>]}> 
        ...
</Frame>
```
<hr>

I believe this explanation will help you. Let me know if this works for you I will create a pull request for the same.

**Comment by builtbyproxy** [comment]
Hey @satendra02 

I can confirm that has fixed all my leaking `css` issues 😲😲❤️ 
If you have the time could you please clarify why that was the case?! 

I have some further questions about bits of the app and advancing functionality. I'd rather not bloat this issue, would you prefer I emailed you or opened additional issues to ask about this functionality? 

Thanks again!

**Comment by satendra02** [comment]
Great! So I will create a pull request and merge it to master. Thanks for your contribution.

> I created this repo 2 years back to help fellow developers so they start creating their extension quickly without going through the configuration setup.

As this repo is just a boilerplate and doesn't have much CSS code, so while testing I didn't realize that it could lead to CSS leakage. I am also using it for my project and fixed this issue earlier but forgot to update it here.

For further questions, you can create an issue so it will help others as well.

**Comment by builtbyproxy** [comment]
Hurray! Thanks a lot @satendra02 
I'll open a few issues shortly, absolutely loving this so far! Thanks again for putting this together

**Comment by 9267aakashsharma** [comment]
Hey @satendra02 

Thanks for posting this solution. I have a little different use-case here. I have tailwind installed to compile the css. So the css file is auto-generated and there is only one file, that it generates. Can you explain a way to decouple, root div css and iframe css, in this case.

**Comment by HarshdipD** [comment]
I'm facing the same issue as @9267aakashsharma. Did you find a solution? Tailwind seems to be generating a <style> in the website directly.

**Comment by satendra02** [comment]
Hey @9267aakashsharma, have you found a solution yet?

I haven't had the chance to use tailwind yet, so it would be really helpful if you could create a sample repository. That way, I can explore and experiment to find potential solutions.
